"use client";

import { ExampleLayout } from "@/src/components/ExampleLayout";
import { ConnectButton } from "@/src/components/ConnectButton";
import { WalletInfo } from "@/src/components/WalletInfo";
import { CodeBlock } from "@/src/components/CodeBlock";
import { useWallet } from "@lazorkit/wallet";
import Swap from "@/src/components/Swap";
const SWAP_CODE = `import { useWallet } from "@lazorkit/wallet";
import { PublicKey } from "@solana/web3.js";
import { getAssociatedTokenAddress, createTransferInstruction } from "@solana/spl-token";

const USDC = new PublicKey("EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v");
const MERCHANT = new PublicKey("EEE2dZ4EHFHmgG24zKgVUutCXQqtYTLJCEAWoNcNAXTj");

export function Swap() {
  const { smartWalletPubkey, signAndSendTransaction } = useWallet();

  async function swap() {
    if (!smartWalletPubkey) return;

    const from = await getAssociatedTokenAddress(USDC, smartWalletPubkey, true);
    const to = await getAssociatedTokenAddress(USDC, MERCHANT, true);

    const ix = createTransferInstruction(from, to, smartWalletPubkey, 5_000_000);

    await signAndSendTransaction({
      instructions: [ix],
      transactionOptions: { feeToken: "USDC" },
    });
  }

  return <button onClick={swap}>Swap USDC → SOL</button>;
}`;


export default function Example04TokenSwap() {
  const { isConnected } = useWallet();

  return (
    <ExampleLayout
      title="Example 04: Basic Token Swap Interface"
      description="This example demonstrates how to build a simple token swap interface using Lazorkit smart wallets, enabling gasless swaps without wallet extensions."
      learnPoints={[
        "Signing swap transactions using Lazorkit smart wallets",
        "Integrating with existing Solana swap protocols",
        "Executing gasless multi-instruction transactions",
        "Abstracting DEX complexity behind a simple UI",
      ]}
      howItWorks={[
        {
          title: "Passkey Authentication",
          text: "The user connects using a Lazorkit passkey-based smart wallet.",
        },
        {
          title: "Swap Instruction Generation",
          text: "Swap instructions are generated by an external DEX aggregator such as Jupiter.",
        },
        {
          title: "Gasless Execution",
          text: "The transaction is signed by the smart wallet and gas fees are sponsored by Lazorkit.",
        },
      ]}
      codeExample={
        <>
          <h2 className="text-xl font-semibold">Code Example</h2>
          <p className="text-sm text-white/60 max-w-2xl">
            Minimal Lazorkit-powered token swap. Developers only need to supply
            swap instructions.
          </p>
          <div className="border border-white/15 rounded-lg p-4">
            <CodeBlock code={SWAP_CODE} />
          </div>
        </>
      }
    >
      <div className="flex flex-col items-center gap-4">
        {!isConnected && <ConnectButton />}
        {isConnected && (
          <div className="flex flex-col items-center gap-4">
            <WalletInfo />
            <Swap />
          </div>
        )}
      </div>
    </ExampleLayout>
  );
}
